import type { ResumeData, ResumeTemplate } from "@/types/resume";

export const TEMPLATES: ResumeTemplate[] = [
  {
    id: "classic",
    name: "Classic",
    category: "Professional",
    atsScore: 98,
    popular: true,
    colors: ["#1a56db", "#374151", "#6b7280"],
    fonts: ["DM Sans"],
    description: "Clean timeless layout — works for any industry",
  },
  {
    id: "executive",
    name: "Executive",
    category: "Executive",
    atsScore: 95,
    colors: ["#1e3a5f", "#b8860b", "#374151"],
    fonts: ["DM Serif Display"],
    description: "Authoritative design for senior & C-suite roles",
  },
  {
    id: "modern",
    name: "Modern",
    category: "Modern",
    atsScore: 90,
    popular: true,
    colors: ["#0f172a", "#6366f1", "#e2e8f0"],
    fonts: ["DM Sans"],
    description: "Sleek contemporary look with bold typography",
  },
  {
    id: "minimal",
    name: "Minimal",
    category: "Minimal",
    atsScore: 96,
    colors: ["#111827", "#d1d5db", "#f9fafb"],
    fonts: ["DM Sans"],
    description: "Ultra-clean, lots of white space, zero clutter",
  },
  {
    id: "tech",
    name: "Tech",
    category: "Modern",
    atsScore: 92,
    popular: true,
    colors: ["#0ea5e9", "#0f172a", "#38bdf8"],
    fonts: ["DM Mono"],
    description: "Built for developers — highlights skills & projects",
  },
  {
    id: "creative",
    name: "Creative",
    category: "Creative",
    atsScore: 78,
    colors: ["#f97316", "#7c3aed", "#fef3c7"],
    fonts: ["DM Serif Display"],
    description: "Bold visual identity for design & media roles",
  },
  {
    id: "ats-pro",
    name: "ATS Pro",
    category: "ATS-Friendly",
    atsScore: 99,
    popular: true,
    colors: ["#374151", "#1a56db", "#f3f4f6"],
    fonts: ["DM Sans"],
    description: "Maximum ATS compatibility, recruiter-tested",
  },
  {
    id: "graduate",
    name: "Graduate",
    category: "Minimal",
    atsScore: 94,
    colors: ["#059669", "#1f2937", "#ecfdf5"],
    fonts: ["DM Sans"],
    description: "Perfect for students and recent graduates",
  },
];

export const DEFAULT_RESUME: ResumeData = {
  templateId: "classic",
  colorScheme: "#1a56db",
  fontFamily: "DM Sans",
  personal: {
    fullName: "",
    title: "",
    email: "",
    phone: "",
    location: "",
    linkedin: "",
    website: "",
  },
  summary: "",
  experience: [],
  education: [],
  skillGroups: [{ id: "sg1", category: "Technical Skills", skills: [] }],
  certifications: [],
  projects: [],
  languages: [],
  references: [],
  sections: [
    { id: "s1", type: "personal",        visible: true, order: 0 },
    { id: "s2", type: "summary",         visible: true, order: 1 },
    { id: "s3", type: "experience",      visible: true, order: 2 },
    { id: "s4", type: "education",       visible: true, order: 3 },
    { id: "s5", type: "skills",          visible: true, order: 4 },
    { id: "s6", type: "certifications",  visible: false, order: 5 },
    { id: "s7", type: "projects",        visible: false, order: 6 },
    { id: "s8", type: "languages",       visible: false, order: 7 },
    { id: "s9", type: "references",      visible: false, order: 8 },
  ],
};
